default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: dmitriybadichan
  password: 123

development:
  <<: *default
  database: job_search_prod
  # database: job_search_prod

staging:
  <<: *default
  database: job_search_stage
  # database: job_search_prod

test:
  <<: *default
  database: job_search_test<%= ENV['TEST_ENV_NUMBER'] %>
# staging:
#   <<: *default
#   database: job_search_prod

# production:
#   <<: *default
#   database: job_search_prod
